# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: pip
    directory: /doc
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily

# Scanning is disabled for files in /test/ to avoid false positives.
# These files are used for testing; vulnerable code is never installed or used.

  - package-ecosystem: cargo
    directory: /test/language_data
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "Inflector"
      - dependency-name: "abort_on_panic"
      - dependency-name: "adler"
      - dependency-name: "adler32"
      - dependency-name: "ahash"
      - dependency-name: "aho-corasick"
      - dependency-name: "ansi_term"
      - dependency-name: "anyhow"
      - dependency-name: "approx"
      - dependency-name: "ascii"
      - dependency-name: "atty"
      - dependency-name: "autocfg"
      - dependency-name: "base64"
      - dependency-name: "bincode"
      - dependency-name: "bitflags"
      - dependency-name: "blake2"
      - dependency-name: "block-buffer"
      - dependency-name: "bstr"
      - dependency-name: "bumpalo"
      - dependency-name: "caseless"
      - dependency-name: "cast"
      - dependency-name: "cc"
      - dependency-name: "cfg-if"
      - dependency-name: "chrono"
      - dependency-name: "clap"
      - dependency-name: "clipboard-win"
      - dependency-name: "console"
      - dependency-name: "console_error_panic_hook"
      - dependency-name: "core-foundation"
      - dependency-name: "core-foundation-sys"
      - dependency-name: "cpufeatures"
      - dependency-name: "cpython"
      - dependency-name: "cranelift"
      - dependency-name: "cranelift-bforest"
      - dependency-name: "cranelift-codegen"
      - dependency-name: "cranelift-codegen-meta"
      - dependency-name: "cranelift-codegen-shared"
      - dependency-name: "cranelift-entity"
      - dependency-name: "cranelift-frontend"
      - dependency-name: "cranelift-jit"
      - dependency-name: "cranelift-module"
      - dependency-name: "cranelift-native"
      - dependency-name: "crc32fast"
      - dependency-name: "criterion"
      - dependency-name: "criterion-plot"
      - dependency-name: "crossbeam-channel"
      - dependency-name: "crossbeam-deque"
      - dependency-name: "crossbeam-epoch"
      - dependency-name: "crossbeam-utils"
      - dependency-name: "crunchy"
      - dependency-name: "crypto-common"
      - dependency-name: "csv"
      - dependency-name: "csv-core"
      - dependency-name: "digest"
      - dependency-name: "dirs-next"
      - dependency-name: "dirs-sys-next"
      - dependency-name: "dns-lookup"
      - dependency-name: "dtoa"
      - dependency-name: "either"
      - dependency-name: "encode_unicode"
      - dependency-name: "endian-type"
      - dependency-name: "env_logger"
      - dependency-name: "error-code"
      - dependency-name: "exitcode"
      - dependency-name: "fd-lock"
      - dependency-name: "flame"
      - dependency-name: "flamer"
      - dependency-name: "flamescope"
      - dependency-name: "flate2"
      - dependency-name: "fnv"
      - dependency-name: "foreign-types"
      - dependency-name: "foreign-types-shared"
      - dependency-name: "generic-array"
      - dependency-name: "gethostname"
      - dependency-name: "getrandom"
      - dependency-name: "half"
      - dependency-name: "hashbrown"
      - dependency-name: "heck"
      - dependency-name: "hermit-abi"
      - dependency-name: "hex"
      - dependency-name: "hexf-parse"
      - dependency-name: "indexmap"
      - dependency-name: "insta"
      - dependency-name: "is-macro"
      - dependency-name: "itertools"
      - dependency-name: "itoa"
      - dependency-name: "itoa"
      - dependency-name: "js-sys"
      - dependency-name: "keccak"
      - dependency-name: "lalrpop-util"
      - dependency-name: "lazy_static"
      - dependency-name: "lazy_static"
      - dependency-name: "lexical-parse-float"
      - dependency-name: "lexical-parse-integer"
      - dependency-name: "lexical-util"
      - dependency-name: "libc"
      - dependency-name: "libffi"
      - dependency-name: "libffi-sys"
      - dependency-name: "libz-sys"
      - dependency-name: "linked-hash-map"
      - dependency-name: "lock_api"
      - dependency-name: "log"
      - dependency-name: "lz4_flex"
      - dependency-name: "mach"
      - dependency-name: "maplit"
      - dependency-name: "matches"
      - dependency-name: "md-5"
      - dependency-name: "memchr"
      - dependency-name: "memmap2"
      - dependency-name: "memoffset"
      - dependency-name: "miniz_oxide"
      - dependency-name: "mt19937"
      - dependency-name: "nibble_vec"
      - dependency-name: "nix"
      - dependency-name: "num-bigint"
      - dependency-name: "num-complex"
      - dependency-name: "num-integer"
      - dependency-name: "num-rational"
      - dependency-name: "num-traits"
      - dependency-name: "num_cpus"
      - dependency-name: "num_enum"
      - dependency-name: "num_enum_derive"
      - dependency-name: "once_cell"
      - dependency-name: "oorandom"
      - dependency-name: "openssl"
      - dependency-name: "openssl-probe"
      - dependency-name: "openssl-src"
      - dependency-name: "openssl-sys"
      - dependency-name: "optional"
      - dependency-name: "page_size"
      - dependency-name: "parking_lot"
      - dependency-name: "parking_lot_core"
      - dependency-name: "paste"
      - dependency-name: "phf"
      - dependency-name: "phf_codegen"
      - dependency-name: "phf_generator"
      - dependency-name: "phf_shared"
      - dependency-name: "pkg-config"
      - dependency-name: "plotters"
      - dependency-name: "plotters-backend"
      - dependency-name: "plotters-svg"
      - dependency-name: "pmutil"
      - dependency-name: "ppv-lite86"
      - dependency-name: "proc-macro-crate"
      - dependency-name: "proc-macro2"
      - dependency-name: "puruspe"
      - dependency-name: "python3-sys"
      - dependency-name: "quote"
      - dependency-name: "radium"
      - dependency-name: "radix_trie"
      - dependency-name: "rand"
      - dependency-name: "rand_chacha"
      - dependency-name: "rand_core"
      - dependency-name: "rayon"
      - dependency-name: "rayon-core"
      - dependency-name: "redox_syscall"
      - dependency-name: "redox_syscall"
      - dependency-name: "redox_users"
      - dependency-name: "regalloc"
      - dependency-name: "regex"
      - dependency-name: "regex-automata"
      - dependency-name: "regex-syntax"
      - dependency-name: "region"
      - dependency-name: "result-like"
      - dependency-name: "result-like-derive"
      - dependency-name: "rustc-hash"
      - dependency-name: "rustc_version"
      - dependency-name: "rustpython"
      - dependency-name: "rustpython-ast"
      - dependency-name: "rustpython-bytecode"
      - dependency-name: "rustpython-common"
      - dependency-name: "rustpython-compiler"
      - dependency-name: "rustpython-compiler-core"
      - dependency-name: "rustpython-derive"
      - dependency-name: "rustpython-doc"
      - dependency-name: "rustpython-jit"
      - dependency-name: "rustpython-parser"
      - dependency-name: "rustpython-pylib"
      - dependency-name: "rustpython-stdlib"
      - dependency-name: "rustpython-vm"
      - dependency-name: "rustpython_wasm"
      - dependency-name: "rustversion"
      - dependency-name: "rustyline"
      - dependency-name: "ryu"
      - dependency-name: "same-file"
      - dependency-name: "schannel"
      - dependency-name: "scopeguard"
      - dependency-name: "semver"
      - dependency-name: "serde"
      - dependency-name: "serde-wasm-bindgen"
      - dependency-name: "serde_cbor"
      - dependency-name: "serde_derive"
      - dependency-name: "serde_json"
      - dependency-name: "serde_yaml"
      - dependency-name: "sha-1"
      - dependency-name: "sha2"
      - dependency-name: "sha3"
      - dependency-name: "similar"
      - dependency-name: "siphasher"
      - dependency-name: "smallvec"
      - dependency-name: "socket2"
      - dependency-name: "sre-engine"
      - dependency-name: "static_assertions"
      - dependency-name: "str-buf"
      - dependency-name: "strsim"
      - dependency-name: "strum"
      - dependency-name: "strum_macros"
      - dependency-name: "subtle"
      - dependency-name: "syn"
      - dependency-name: "syn-ext"
      - dependency-name: "system-configuration"
      - dependency-name: "system-configuration-sys"
      - dependency-name: "target-lexicon"
      - dependency-name: "termcolor"
      - dependency-name: "terminal_size"
      - dependency-name: "termios"
      - dependency-name: "textwrap"
      - dependency-name: "textwrap"
      - dependency-name: "thiserror"
      - dependency-name: "thiserror-impl"
      - dependency-name: "thread-id"
      - dependency-name: "thread_local"
      - dependency-name: "time"
      - dependency-name: "timsort"
      - dependency-name: "tiny-keccak"
      - dependency-name: "tinytemplate"
      - dependency-name: "tinyvec"
      - dependency-name: "tinyvec_macros"
      - dependency-name: "toml"
      - dependency-name: "twox-hash"
      - dependency-name: "typenum"
      - dependency-name: "uname"
      - dependency-name: "unic-char-property"
      - dependency-name: "unic-char-range"
      - dependency-name: "unic-common"
      - dependency-name: "unic-emoji-char"
      - dependency-name: "unic-normal"
      - dependency-name: "unic-ucd-age"
      - dependency-name: "unic-ucd-bidi"
      - dependency-name: "unic-ucd-category"
      - dependency-name: "unic-ucd-hangul"
      - dependency-name: "unic-ucd-ident"
      - dependency-name: "unic-ucd-normal"
      - dependency-name: "unic-ucd-version"
      - dependency-name: "unicode-casing"
      - dependency-name: "unicode-normalization"
      - dependency-name: "unicode-segmentation"
      - dependency-name: "unicode-width"
      - dependency-name: "unicode-xid"
      - dependency-name: "unicode_names2"
      - dependency-name: "utf8parse"
      - dependency-name: "vcpkg"
      - dependency-name: "vec_map"
      - dependency-name: "version_check"
      - dependency-name: "volatile"
      - dependency-name: "walkdir"
      - dependency-name: "wasi"
      - dependency-name: "wasm-bindgen"
      - dependency-name: "wasm-bindgen-backend"
      - dependency-name: "wasm-bindgen-futures"
      - dependency-name: "wasm-bindgen-macro"
      - dependency-name: "wasm-bindgen-macro-support"
      - dependency-name: "wasm-bindgen-shared"
      - dependency-name: "web-sys"
      - dependency-name: "which"
      - dependency-name: "widestring"
      - dependency-name: "winapi"
      - dependency-name: "winapi-i686-pc-windows-gnu"
      - dependency-name: "winapi-util"
      - dependency-name: "winapi-x86_64-pc-windows-gnu"
      - dependency-name: "windows-sys"
      - dependency-name: "windows_aarch64_msvc"
      - dependency-name: "windows_i686_gnu"
      - dependency-name: "windows_i686_msvc"
      - dependency-name: "windows_x86_64_gnu"
      - dependency-name: "windows_x86_64_msvc"
      - dependency-name: "winreg"
      - dependency-name: "xml-rs"
      - dependency-name: "yaml-rust"

  - package-ecosystem: bundler
    directory: /test/language_data
    schedule:
      interval: monthly

  - package-ecosystem: gomod
    directory: /test/language_data
    schedule:
      interval: monthly

  - package-ecosystem: pip
    directory: /test/language_data
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "rich"
      - dependency-name: "plotly"
      - dependency-name: "jinja2"
      - dependency-name: "beautifulsoup4"
      - dependency-name: "aiohttp[speedups]"
      - dependency-name: "toml"
      - dependency-name: "pyyaml"
      - dependency-name: "jsonschema"
      - dependency-name: "rpmfile"
      - dependency-name: "zstandard"
      - dependency-name: "distro"
      - dependency-name: "defusedxml"
      - dependency-name: "xmlschema"
      - dependency-name: "importlib_metadata"
      - dependency-name: "requests"
      - dependency-name: "urllib3"
      - dependency-name: "gsutil"
      - dependency-name: "cvss"
      - dependency-name: "packaging"

  - package-ecosystem: maven
    directory: /test/language_data
    schedule:
      interval: never

