# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: pip
    directory: /doc
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: /test/language_data
    schedule:
      interval: daily

  - package-ecosystem: bundler
    directory: /test/language_data
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /test/language_data
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /test/language_data
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /test/language_data
    schedule:
      interval: daily
