# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: pip
    directory: /doc
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily

# Scanning is disabled for files in /test/ to avoid false positives.
# These files are used for testing; vulnerable code is never installed or used.

  - package-ecosystem: cargo
    directory: /test/language_data
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "*"

  - package-ecosystem: bundler
    directory: /test/language_data
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "*"

  - package-ecosystem: gomod
    directory: /test/language_data
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "*"

  - package-ecosystem: pip
    directory: /test/language_data
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "*"

  - package-ecosystem: maven
    directory: /test/language_data
    schedule:
      interval: monthly
    ignore:
      - dependency-name: "*"

