language: python
addons:
  apt:
    packages:
      - file
      - binutils
      - tar
      - unzip
      - rpm2cpio
      - cpio
      - cabextract
      - openssl
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# 3.7 fails with: Unable to download 3.7 archive. The archive may not exist.
# Please consider a different version.
# - "3.7"
matrix:
  include:
    - python: '3.6'
      script:
        - pip install black
        - black --check cve_bin_tool/
        - black --check test/
script:
  - pip install codecov coverage jsonschema
  - travis_wait 30 LONG_TESTS=1 coverage run setup.py test
  - coverage report -m
  - pip install -e .
  - pip install -e example/oot-checker
  - cve-bin-tool -l info $(mktemp -d) 2>&1 | grep 'loaded:' | grep checker_name
cache:
  directories:
    - $HOME/.cache/cve-bin-tool
after_success:
  - codecov
