language: python
addons:
  apt:
    packages:
      - file
      - binutils
      - tar
      - unzip
      - rpm2cpio
      - cpio
      - cabextract
      - openssl
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# 3.7 fails with: Unable to download 3.7 archive. The archive may not exist.
# Please consider a different version.
# - "3.7"
script:
  - python setup.py test
  - pip install -e .
  - pip install -e example/oot-checker
  - pip install codecov
  - cve-bin-tool -l info $(mktemp -d) 2>&1 | grep 'loaded:' | grep checker_name
cache:
  directories:
    - $HOME/.cache/cve-bin-tool
after_success:
  - codecov
