name: CVE Binary Tool Scanner

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    permissions:
      security-events: write
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-ubuntu-latest' || 'ubuntu-latest' }}
    steps:
      - uses: intel/cve-bin-tool-action@main
        with:
          exclude_dir: test
          vex_file: TRIAGE.json
